### PR TITLE
Enhance Activation Button Functionality for Starlink Kits

### LINKED ISSUE #47: Improve ACTIVATE KITS behaviour
# 📂  Expectation

When a user clicks the **Activate** button on a kit:

- The button text should change to **"Activating..."** and become **disabled** while the API call is being processed.
- If the activation **fails**, the button should revert back to **"Activate"** and remain clickable.
- If the activation **succeeds**, the button should update to **"Manage"** (as it currently does), and the **Status** should immediately change to **"Online"** without requiring a page reload.#46 
 
# 💡 
## Working Branch
```
git fetch origin
git checkout resolve-issue-47
```

## PRs
**Base branch**: `dev`
**Title**: [Issue-47]: Improve ACIVATE KITS behaviour
**Description**: A summary of what has been done and the impact [Feestyle]

Image

### PR DESCRIPTION
**Pull request by olanikegloria**
This PR provides these improvements:

1. **Button State Management**:
   - The "Activate" button now displays "Activating..." and becomes disabled while the activation API call is in progress.
   - If the activation fails, the button reverts back to "Activate" and remains clickable.

2. **Immediate Status Update**:
   - Upon successful activation, the button updates to "Manage" and the kit's status changes to "Online" without requiring a page reload.
Proper error handling has been added to display appropriate messages for activation failures, including insufficient funds.

3 **Code Improvements**:
   - Updated the `handleActivateKit` function to manage state effectively and ensure seamless UI updates.
   - Enhanced the `mapStatus` function to correctly map statuses for immediate UI feedback.

### CODE REVIEW

File: src/pages/Home.jsx [hunk 1]
```diff
@@ -245,18 +248,26 @@ const Home = () => {
...
         prevStarlinks.map((starlink) =>
-          starlink.id === kitId ? { ...starlink, status: "approved" } : starlink
+          starlink.id === kitId ? { ...starlink, status: "active" } : starlink
+        )
+      );
+      
+      // Also update in filtered starlinks
+      setFilteredStarlinks((prevFiltered) =>
+        prevFiltered.map((starlink) =>
+          starlink.id === kitId ? { ...starlink, status: "active" } : starlink
```
Comment (geekelo) [inline src/pages/Home.jsx:264]: Are you displaying active kits first here? @olanikegloria

**Review by geekelo — APPROVED** [review]
Moving Forward :rocket:
